version: "2"
services:
    # the database image
    devdb:
        image: "postgres:9.4"
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: devdb
            POSTGRES_PASSWORD: devdb
        volumes_from:
            - dbdata

    # for persistence of database data
    dbdata:
        image: "postgres:9.4"
        volumes:
            - /var/lib/postgres
        command: "true"

    # the main image, this is the application
    web:
        command: bash
        stdin_open: true
        tty: true
        user: $UID

        build:
            context: .
            dockerfile: ./Dockerfile.dev

        ports:
            - "4000:4000"
            - "9485:9485"
        links:
            - "devdb:devdb"
        volumes:
            - ./:/app
        working_dir: /app
        depends_on:
            - devdb
